version: "3"
services:
    hub:
        image: selenium/hub:4.10.0
        # ports: 
        # - 4444:4444
    chrome:
        image: selenium/node-chrome:4.10
        shm_size: '2g'
        depends_on:
        - hub
        environment:
        - SE_EVENT_BUS_HOST=hub # BY specifiing the ports the chrome container can talk to hub container
        - SE_EVENT_BUS_PUBLISH_PORT=4442 #PORT 
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    firefox:
        image: selenium/node-firefox:4.10
        depends_on:
        - hub
        environment:
        - SE_EVENT_BUS_HOST=hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442 
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    
        #comments
# Since we use grid, we can add browsers 
# using environment variables in eache brawser we can tell the browser how to connect to hub
# In this yaml file we can specify diferent browser version, and diferent browser types.